enableTelemetry: false

logFilters:
  - code: YN0062
    level: discard
  - code: YN0002
    level: info

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

pnpEnableEsmLoader: false

yarnPath: .yarn/releases/yarn-3.2.2.cjs