compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

logFilters:
  - code: YN0062
    level: discard
  - code: YN0002
    level: info

nodeLinker: node-modules

pnpEnableEsmLoader: false

supportedArchitectures:
  cpu:
    - x64
  libc:
    - glibc
  os:
    - linux

yarnPath: .yarn/releases/yarn-4.12.0.cjs
