apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2021-04-22T06:20:12Z"
  labels:
    k8s-app: submelon-tech
  name: submelon-tech
  namespace: default
  uid: 60ce2fb5-2fc4-4909-858c-fb76be2ecdf4
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: submelon-tech
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: submelon-tech
      name: submelon-tech
    spec:
      containers:
      - image: registry.digitalocean.com/submelon-tech/submelon.tech:1.0.0
        imagePullPolicy: Always
        name: submelon-tech
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            memory: 128Mi
            cpu: 500m
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: doreg
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
