name: submelon.dev build

on:
  push:
    branches: [ "trunk" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Commit public changes
      uses: EndBug/add-and-commit@v9
      with:
        add: 'public'
        author_name: "Kevin J Hoerr"
        author_email: "kjhoerr@protonmail.com"
        commit: --signoff
        message: 'Commit from GitHub Actions (updated public build)'
