name: submelon.dev build

on:
  push:
    branches: [ "trunk" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Node.js packages
      run: npm ci

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%s')"
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          source:
            - 'src/**'
    # modify version number if actual source files changed
    - name: Modify version number
      uses: mingjun97/file-regex-replace@v1
      if: steps.filter.outputs.source == 'true'
      with:
        regex: 'version: "[0-9]*",'
        replacement: 'version: "${{ steps.date.outputs.date }}",'
        include: 'gatsby-config\.ts'

    - name: Clean Gatsby cache
      run: npm run clean
    - name: Run Gatsby Build
      run: npm run build --if-present
    - name: Commit public changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: trunk
