name: submelon.dev PR

on:
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Check changes (prevent pushing to public/)
      run: |
        [[ -z "$(git diff --raw trunk -- public/)" ]]
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Node.js packages
      run: npm ci
    - name: Run linter
      run: npm run lint
