name: submelon.dev PR

on:
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    - name: Check changes (prevent pushing to public/)
      uses: xalvarez/prevent-file-change-action@v1.5.1
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        pattern: public/
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Install Node.js packages
      run: yarn install --immutable --immutable-cache --check-cache
    - name: Run test build
      run: yarn build